// Generated by LiveScript 1.2.0
(function(){
  var fs, count, data_dir, cache_dir, output_file, output_fields, base_uri, uri, parseCases, parser;
  fs = require('fs');
  count = 0;
  data_dir = '..';
  cache_dir = 'cache';
  output_file = data_dir + '/index.json';
  output_fields = ['id', 'href', 'category', 'ann_type', 'type', 'administrasion', 'times', 'start_from', 'end_at'];
  base_uri = 'http://ppp.pcc.gov.tw/PPP.Website/Case';
  uri = base_uri + '/AnnounceView.aspx';
  parseCases = function(crawler, $){};
  parser = function(crawler){
    var data, ending, cb;
    data = [];
    ending = function(){
      return fs.writeFileSync(output_file, JSON.stringify(
      data));
    };
    return cb = function(err, result, $){
      var addIndex, crawlNextPage;
      addIndex = function(){
        $('.SecondTable').first().next().children().each(function(i){
          var d;
          if ($(this).children('th').size > 0) {
            return;
          }
          d = {};
          d.uri = base_uri + '/' + $(this).children('td').first().next().children('a').attr('href');
          d.title = $(this).children('td').first().next().text();
          if (!d.title) {
            return;
          }
          $(this).children('td').each(function(i){
            d[output_fields[i]] = $(this).text();
          });
          data.push(d);
          console.log(
          d.title);
        });
      };
      crawlNextPage = function(){
        var postarg;
        postarg = {
          __EVENTTARGET: 'ctl00$MainPlaceHolder$PagerList1$btnNext',
          __VIEWSTATE: $('#__VIEWSTATE').val(),
          __EVENTVALIDATION: $('#__EVENTVALIDATION').val()
        };
        crawler.queue([{
          uri: uri,
          method: 'post',
          form: postarg,
          callback: cb
        }]);
      };
      addIndex();
      if ($('#ctl00_MainPlaceHolder_PagerList1_btnNext').attr('disabled')) {
        ending();
        return;
      }
      crawlNextPage();
    };
  };
  exports.parser = parser;
}).call(this);
